### ISSUE TITLE
Error when applying plugin

### ISSUE THREAD

**Issue by luiscruz** [walkmod/walkmod-refactor-plugin#1]
I am trying to apply **Refactor** to the [quickstart project](https://github.com/walkmod/quickstart.git).

After running

```
walkmod add -DrefactoringConfigFile="src/main/walkmod/refactor/refactoring-methods.json" refactor:methods
```

My `walkmod.xml` file looks like this:

```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <transformation type="imports-cleaner"/>
    <transformation type="refactor:methods">
        <param name="refactoringConfigFile">src/main/walkmod/refactor/refactoring-methods.json</param>
    </transformation>
</walkmod>
```

However, when running `walkmod apply` I get the following error:

```
ERROR [main] - TRANSFORMATION CHAIN (default) FAILS
An exeception has been produced during the null transformation - org.walkmod.util.location.LocationImpl@1eef9aef
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:261)
        at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:276)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.execute(DefaultJavaWalker.java:160)
        at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:41)
        at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
        at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:165)
        at org.walkmod.WalkModFacade.executeAllChains(WalkModFacade.java:911)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:376)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
Caused by: java.lang.reflect.InvocationTargetException
        ... 15 more
Caused by: Error processing [/Users/cruz/dev/quickstart/src/main/java/org/walkmod/quickstart/model/Tweet.java] - org.walkmod.util.location.LocationImpl@3ec11999
        at org.walkmod.refactor.config.RefactoringRulesDictionary.putRules(RefactoringRulesDictionary.java:95)
        at org.walkmod.refactor.visitors.MethodRefactor.visit(MethodRefactor.java:103)
        at org.walkmod.refactor.visitors.MethodRefactor.visit(MethodRefactor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:123)
        at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:172)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:397)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:224)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.accept(DefaultJavaWalker.java:86)
        ... 15 more
Caused by: java.lang.NullPointerException
        ... 27 more
```

Any ideas?

**Comment by rpau** [comment]
Hi,

What rules have you put in the src/main/walkmod/refactor/refactoring-methods.json file?

**Comment by luiscruz** [comment]
Ham, probably I've skipped some step.
I don't have the file you mentioned:

```
$ ls src/main/
scripts   templates
```

**Comment by rpau** [comment]
In your walkmod.xml file, you have defined a json file with the refactorings: 

<param name="refactoringConfigFile">src/main/walkmod/refactor/refactoring-methods.json</param>

Read the README of this project (https://github.com/walkmod/walkmod-refactor-plugin), because explains an example about how to use this plugin.

**Comment by luiscruz** [comment]
Ok, now I get it..
I've read the README but it was not clear to me that I had to create this file.
Thanks!

**Comment by rpau** [comment]
Just a comment, the quickstart project is nice because shows how to use different kind of transformations. 

So, be sure that the refactorings you apply are classes that are used in the project. I personally recommend to play with a blank maven project that allows you to verify that the applied refactoring are those you want :) 

Enjoy!

**Comment by luiscruz** [comment]
Alright! Thanks 👍
